/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RootRouteRouteImport } from './routes/_root/route'
import { Route as RootIndexRouteImport } from './routes/_root/index'
import { Route as RundownRundownIdRouteImport } from './routes/rundown/$rundownId'
import { Route as RootSettingsRouteImport } from './routes/_root/settings'
import { Route as RundownRundownIdIndexRouteImport } from './routes/rundown/$rundownId/index'
import { Route as RootSettingsIndexRouteImport } from './routes/_root/settings/index'
import { Route as RootSettingsRundownRouteImport } from './routes/_root/settings/rundown'
import { Route as RootSettingsConnectionRouteImport } from './routes/_root/settings/connection'
import { Route as RootSettingsTypeTypeRouteImport } from './routes/_root/settings/type/$type'
import { Route as RundownRundownIdSegmentSegmentIdIndexRouteImport } from './routes/rundown/$rundownId/segment/$segmentId/index'
import { Route as RundownRundownIdSegmentSegmentIdPartPartIdIndexRouteImport } from './routes/rundown/$rundownId/segment/$segmentId/part/$partId/index'
import { Route as RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRouteImport } from './routes/rundown/$rundownId/segment/$segmentId/part/$partId/piece/$pieceId'

const RootRouteRoute = RootRouteRouteImport.update({
  id: '/_root',
  getParentRoute: () => rootRouteImport,
} as any)
const RootIndexRoute = RootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootRouteRoute,
} as any)
const RundownRundownIdRoute = RundownRundownIdRouteImport.update({
  id: '/rundown/$rundownId',
  path: '/rundown/$rundownId',
  getParentRoute: () => rootRouteImport,
} as any)
const RootSettingsRoute = RootSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RootRouteRoute,
} as any)
const RundownRundownIdIndexRoute = RundownRundownIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RundownRundownIdRoute,
} as any)
const RootSettingsIndexRoute = RootSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootSettingsRoute,
} as any)
const RootSettingsRundownRoute = RootSettingsRundownRouteImport.update({
  id: '/rundown',
  path: '/rundown',
  getParentRoute: () => RootSettingsRoute,
} as any)
const RootSettingsConnectionRoute = RootSettingsConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => RootSettingsRoute,
} as any)
const RootSettingsTypeTypeRoute = RootSettingsTypeTypeRouteImport.update({
  id: '/type/$type',
  path: '/type/$type',
  getParentRoute: () => RootSettingsRoute,
} as any)
const RundownRundownIdSegmentSegmentIdIndexRoute =
  RundownRundownIdSegmentSegmentIdIndexRouteImport.update({
    id: '/segment/$segmentId/',
    path: '/segment/$segmentId/',
    getParentRoute: () => RundownRundownIdRoute,
  } as any)
const RundownRundownIdSegmentSegmentIdPartPartIdIndexRoute =
  RundownRundownIdSegmentSegmentIdPartPartIdIndexRouteImport.update({
    id: '/segment/$segmentId/part/$partId/',
    path: '/segment/$segmentId/part/$partId/',
    getParentRoute: () => RundownRundownIdRoute,
  } as any)
const RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRoute =
  RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRouteImport.update({
    id: '/segment/$segmentId/part/$partId/piece/$pieceId',
    path: '/segment/$segmentId/part/$partId/piece/$pieceId',
    getParentRoute: () => RundownRundownIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof RootSettingsRouteWithChildren
  '/rundown/$rundownId': typeof RundownRundownIdRouteWithChildren
  '/': typeof RootIndexRoute
  '/settings/connection': typeof RootSettingsConnectionRoute
  '/settings/rundown': typeof RootSettingsRundownRoute
  '/settings/': typeof RootSettingsIndexRoute
  '/rundown/$rundownId/': typeof RundownRundownIdIndexRoute
  '/settings/type/$type': typeof RootSettingsTypeTypeRoute
  '/rundown/$rundownId/segment/$segmentId': typeof RundownRundownIdSegmentSegmentIdIndexRoute
  '/rundown/$rundownId/segment/$segmentId/part/$partId': typeof RundownRundownIdSegmentSegmentIdPartPartIdIndexRoute
  '/rundown/$rundownId/segment/$segmentId/part/$partId/piece/$pieceId': typeof RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof RootIndexRoute
  '/settings/connection': typeof RootSettingsConnectionRoute
  '/settings/rundown': typeof RootSettingsRundownRoute
  '/settings': typeof RootSettingsIndexRoute
  '/rundown/$rundownId': typeof RundownRundownIdIndexRoute
  '/settings/type/$type': typeof RootSettingsTypeTypeRoute
  '/rundown/$rundownId/segment/$segmentId': typeof RundownRundownIdSegmentSegmentIdIndexRoute
  '/rundown/$rundownId/segment/$segmentId/part/$partId': typeof RundownRundownIdSegmentSegmentIdPartPartIdIndexRoute
  '/rundown/$rundownId/segment/$segmentId/part/$partId/piece/$pieceId': typeof RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_root': typeof RootRouteRouteWithChildren
  '/_root/settings': typeof RootSettingsRouteWithChildren
  '/rundown/$rundownId': typeof RundownRundownIdRouteWithChildren
  '/_root/': typeof RootIndexRoute
  '/_root/settings/connection': typeof RootSettingsConnectionRoute
  '/_root/settings/rundown': typeof RootSettingsRundownRoute
  '/_root/settings/': typeof RootSettingsIndexRoute
  '/rundown/$rundownId/': typeof RundownRundownIdIndexRoute
  '/_root/settings/type/$type': typeof RootSettingsTypeTypeRoute
  '/rundown/$rundownId/segment/$segmentId/': typeof RundownRundownIdSegmentSegmentIdIndexRoute
  '/rundown/$rundownId/segment/$segmentId/part/$partId/': typeof RundownRundownIdSegmentSegmentIdPartPartIdIndexRoute
  '/rundown/$rundownId/segment/$segmentId/part/$partId/piece/$pieceId': typeof RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/rundown/$rundownId'
    | '/'
    | '/settings/connection'
    | '/settings/rundown'
    | '/settings/'
    | '/rundown/$rundownId/'
    | '/settings/type/$type'
    | '/rundown/$rundownId/segment/$segmentId'
    | '/rundown/$rundownId/segment/$segmentId/part/$partId'
    | '/rundown/$rundownId/segment/$segmentId/part/$partId/piece/$pieceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/connection'
    | '/settings/rundown'
    | '/settings'
    | '/rundown/$rundownId'
    | '/settings/type/$type'
    | '/rundown/$rundownId/segment/$segmentId'
    | '/rundown/$rundownId/segment/$segmentId/part/$partId'
    | '/rundown/$rundownId/segment/$segmentId/part/$partId/piece/$pieceId'
  id:
    | '__root__'
    | '/_root'
    | '/_root/settings'
    | '/rundown/$rundownId'
    | '/_root/'
    | '/_root/settings/connection'
    | '/_root/settings/rundown'
    | '/_root/settings/'
    | '/rundown/$rundownId/'
    | '/_root/settings/type/$type'
    | '/rundown/$rundownId/segment/$segmentId/'
    | '/rundown/$rundownId/segment/$segmentId/part/$partId/'
    | '/rundown/$rundownId/segment/$segmentId/part/$partId/piece/$pieceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RootRouteRoute: typeof RootRouteRouteWithChildren
  RundownRundownIdRoute: typeof RundownRundownIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_root': {
      id: '/_root'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root/': {
      id: '/_root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootIndexRouteImport
      parentRoute: typeof RootRouteRoute
    }
    '/rundown/$rundownId': {
      id: '/rundown/$rundownId'
      path: '/rundown/$rundownId'
      fullPath: '/rundown/$rundownId'
      preLoaderRoute: typeof RundownRundownIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root/settings': {
      id: '/_root/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof RootSettingsRouteImport
      parentRoute: typeof RootRouteRoute
    }
    '/rundown/$rundownId/': {
      id: '/rundown/$rundownId/'
      path: '/'
      fullPath: '/rundown/$rundownId/'
      preLoaderRoute: typeof RundownRundownIdIndexRouteImport
      parentRoute: typeof RundownRundownIdRoute
    }
    '/_root/settings/': {
      id: '/_root/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof RootSettingsIndexRouteImport
      parentRoute: typeof RootSettingsRoute
    }
    '/_root/settings/rundown': {
      id: '/_root/settings/rundown'
      path: '/rundown'
      fullPath: '/settings/rundown'
      preLoaderRoute: typeof RootSettingsRundownRouteImport
      parentRoute: typeof RootSettingsRoute
    }
    '/_root/settings/connection': {
      id: '/_root/settings/connection'
      path: '/connection'
      fullPath: '/settings/connection'
      preLoaderRoute: typeof RootSettingsConnectionRouteImport
      parentRoute: typeof RootSettingsRoute
    }
    '/_root/settings/type/$type': {
      id: '/_root/settings/type/$type'
      path: '/type/$type'
      fullPath: '/settings/type/$type'
      preLoaderRoute: typeof RootSettingsTypeTypeRouteImport
      parentRoute: typeof RootSettingsRoute
    }
    '/rundown/$rundownId/segment/$segmentId/': {
      id: '/rundown/$rundownId/segment/$segmentId/'
      path: '/segment/$segmentId'
      fullPath: '/rundown/$rundownId/segment/$segmentId'
      preLoaderRoute: typeof RundownRundownIdSegmentSegmentIdIndexRouteImport
      parentRoute: typeof RundownRundownIdRoute
    }
    '/rundown/$rundownId/segment/$segmentId/part/$partId/': {
      id: '/rundown/$rundownId/segment/$segmentId/part/$partId/'
      path: '/segment/$segmentId/part/$partId'
      fullPath: '/rundown/$rundownId/segment/$segmentId/part/$partId'
      preLoaderRoute: typeof RundownRundownIdSegmentSegmentIdPartPartIdIndexRouteImport
      parentRoute: typeof RundownRundownIdRoute
    }
    '/rundown/$rundownId/segment/$segmentId/part/$partId/piece/$pieceId': {
      id: '/rundown/$rundownId/segment/$segmentId/part/$partId/piece/$pieceId'
      path: '/segment/$segmentId/part/$partId/piece/$pieceId'
      fullPath: '/rundown/$rundownId/segment/$segmentId/part/$partId/piece/$pieceId'
      preLoaderRoute: typeof RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRouteImport
      parentRoute: typeof RundownRundownIdRoute
    }
  }
}

interface RootSettingsRouteChildren {
  RootSettingsConnectionRoute: typeof RootSettingsConnectionRoute
  RootSettingsRundownRoute: typeof RootSettingsRundownRoute
  RootSettingsIndexRoute: typeof RootSettingsIndexRoute
  RootSettingsTypeTypeRoute: typeof RootSettingsTypeTypeRoute
}

const RootSettingsRouteChildren: RootSettingsRouteChildren = {
  RootSettingsConnectionRoute: RootSettingsConnectionRoute,
  RootSettingsRundownRoute: RootSettingsRundownRoute,
  RootSettingsIndexRoute: RootSettingsIndexRoute,
  RootSettingsTypeTypeRoute: RootSettingsTypeTypeRoute,
}

const RootSettingsRouteWithChildren = RootSettingsRoute._addFileChildren(
  RootSettingsRouteChildren,
)

interface RootRouteRouteChildren {
  RootSettingsRoute: typeof RootSettingsRouteWithChildren
  RootIndexRoute: typeof RootIndexRoute
}

const RootRouteRouteChildren: RootRouteRouteChildren = {
  RootSettingsRoute: RootSettingsRouteWithChildren,
  RootIndexRoute: RootIndexRoute,
}

const RootRouteRouteWithChildren = RootRouteRoute._addFileChildren(
  RootRouteRouteChildren,
)

interface RundownRundownIdRouteChildren {
  RundownRundownIdIndexRoute: typeof RundownRundownIdIndexRoute
  RundownRundownIdSegmentSegmentIdIndexRoute: typeof RundownRundownIdSegmentSegmentIdIndexRoute
  RundownRundownIdSegmentSegmentIdPartPartIdIndexRoute: typeof RundownRundownIdSegmentSegmentIdPartPartIdIndexRoute
  RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRoute: typeof RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRoute
}

const RundownRundownIdRouteChildren: RundownRundownIdRouteChildren = {
  RundownRundownIdIndexRoute: RundownRundownIdIndexRoute,
  RundownRundownIdSegmentSegmentIdIndexRoute:
    RundownRundownIdSegmentSegmentIdIndexRoute,
  RundownRundownIdSegmentSegmentIdPartPartIdIndexRoute:
    RundownRundownIdSegmentSegmentIdPartPartIdIndexRoute,
  RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRoute:
    RundownRundownIdSegmentSegmentIdPartPartIdPiecePieceIdRoute,
}

const RundownRundownIdRouteWithChildren =
  RundownRundownIdRoute._addFileChildren(RundownRundownIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  RootRouteRoute: RootRouteRouteWithChildren,
  RundownRundownIdRoute: RundownRundownIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
