/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootRouteImport } from './routes/_root/route'
import { Route as RootIndexImport } from './routes/_root/index'
import { Route as RundownRundownIdImport } from './routes/rundown/$rundownId'
import { Route as RootSettingsImport } from './routes/_root/settings'
import { Route as RundownRundownIdIndexImport } from './routes/rundown/$rundownId/index'
import { Route as RundownRundownIdSegmentSegmentIdIndexImport } from './routes/rundown/$rundownId/segment/$segmentId/index'

// Create/Update Routes

const RootRouteRoute = RootRouteImport.update({
  id: '/_root',
  getParentRoute: () => rootRoute,
} as any)

const RootIndexRoute = RootIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootRouteRoute,
} as any)

const RundownRundownIdRoute = RundownRundownIdImport.update({
  id: '/rundown/$rundownId',
  path: '/rundown/$rundownId',
  getParentRoute: () => rootRoute,
} as any)

const RootSettingsRoute = RootSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RootRouteRoute,
} as any)

const RundownRundownIdIndexRoute = RundownRundownIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RundownRundownIdRoute,
} as any)

const RundownRundownIdSegmentSegmentIdIndexRoute =
  RundownRundownIdSegmentSegmentIdIndexImport.update({
    id: '/segment/$segmentId/',
    path: '/segment/$segmentId/',
    getParentRoute: () => RundownRundownIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_root': {
      id: '/_root'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootRouteImport
      parentRoute: typeof rootRoute
    }
    '/_root/settings': {
      id: '/_root/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof RootSettingsImport
      parentRoute: typeof RootRouteImport
    }
    '/rundown/$rundownId': {
      id: '/rundown/$rundownId'
      path: '/rundown/$rundownId'
      fullPath: '/rundown/$rundownId'
      preLoaderRoute: typeof RundownRundownIdImport
      parentRoute: typeof rootRoute
    }
    '/_root/': {
      id: '/_root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootIndexImport
      parentRoute: typeof RootRouteImport
    }
    '/rundown/$rundownId/': {
      id: '/rundown/$rundownId/'
      path: '/'
      fullPath: '/rundown/$rundownId/'
      preLoaderRoute: typeof RundownRundownIdIndexImport
      parentRoute: typeof RundownRundownIdImport
    }
    '/rundown/$rundownId/segment/$segmentId/': {
      id: '/rundown/$rundownId/segment/$segmentId/'
      path: '/segment/$segmentId'
      fullPath: '/rundown/$rundownId/segment/$segmentId'
      preLoaderRoute: typeof RundownRundownIdSegmentSegmentIdIndexImport
      parentRoute: typeof RundownRundownIdImport
    }
  }
}

// Create and export the route tree

interface RootRouteRouteChildren {
  RootSettingsRoute: typeof RootSettingsRoute
  RootIndexRoute: typeof RootIndexRoute
}

const RootRouteRouteChildren: RootRouteRouteChildren = {
  RootSettingsRoute: RootSettingsRoute,
  RootIndexRoute: RootIndexRoute,
}

const RootRouteRouteWithChildren = RootRouteRoute._addFileChildren(
  RootRouteRouteChildren,
)

interface RundownRundownIdRouteChildren {
  RundownRundownIdIndexRoute: typeof RundownRundownIdIndexRoute
  RundownRundownIdSegmentSegmentIdIndexRoute: typeof RundownRundownIdSegmentSegmentIdIndexRoute
}

const RundownRundownIdRouteChildren: RundownRundownIdRouteChildren = {
  RundownRundownIdIndexRoute: RundownRundownIdIndexRoute,
  RundownRundownIdSegmentSegmentIdIndexRoute:
    RundownRundownIdSegmentSegmentIdIndexRoute,
}

const RundownRundownIdRouteWithChildren =
  RundownRundownIdRoute._addFileChildren(RundownRundownIdRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof RootRouteRouteWithChildren
  '/settings': typeof RootSettingsRoute
  '/rundown/$rundownId': typeof RundownRundownIdRouteWithChildren
  '/': typeof RootIndexRoute
  '/rundown/$rundownId/': typeof RundownRundownIdIndexRoute
  '/rundown/$rundownId/segment/$segmentId': typeof RundownRundownIdSegmentSegmentIdIndexRoute
}

export interface FileRoutesByTo {
  '/settings': typeof RootSettingsRoute
  '/': typeof RootIndexRoute
  '/rundown/$rundownId': typeof RundownRundownIdIndexRoute
  '/rundown/$rundownId/segment/$segmentId': typeof RundownRundownIdSegmentSegmentIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_root': typeof RootRouteRouteWithChildren
  '/_root/settings': typeof RootSettingsRoute
  '/rundown/$rundownId': typeof RundownRundownIdRouteWithChildren
  '/_root/': typeof RootIndexRoute
  '/rundown/$rundownId/': typeof RundownRundownIdIndexRoute
  '/rundown/$rundownId/segment/$segmentId/': typeof RundownRundownIdSegmentSegmentIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/settings'
    | '/rundown/$rundownId'
    | '/'
    | '/rundown/$rundownId/'
    | '/rundown/$rundownId/segment/$segmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/'
    | '/rundown/$rundownId'
    | '/rundown/$rundownId/segment/$segmentId'
  id:
    | '__root__'
    | '/_root'
    | '/_root/settings'
    | '/rundown/$rundownId'
    | '/_root/'
    | '/rundown/$rundownId/'
    | '/rundown/$rundownId/segment/$segmentId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RootRouteRoute: typeof RootRouteRouteWithChildren
  RundownRundownIdRoute: typeof RundownRundownIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  RootRouteRoute: RootRouteRouteWithChildren,
  RundownRundownIdRoute: RundownRundownIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_root",
        "/rundown/$rundownId"
      ]
    },
    "/_root": {
      "filePath": "_root/route.tsx",
      "children": [
        "/_root/settings",
        "/_root/"
      ]
    },
    "/_root/settings": {
      "filePath": "_root/settings.tsx",
      "parent": "/_root"
    },
    "/rundown/$rundownId": {
      "filePath": "rundown/$rundownId.tsx",
      "children": [
        "/rundown/$rundownId/",
        "/rundown/$rundownId/segment/$segmentId/"
      ]
    },
    "/_root/": {
      "filePath": "_root/index.tsx",
      "parent": "/_root"
    },
    "/rundown/$rundownId/": {
      "filePath": "rundown/$rundownId/index.tsx",
      "parent": "/rundown/$rundownId"
    },
    "/rundown/$rundownId/segment/$segmentId/": {
      "filePath": "rundown/$rundownId/segment/$segmentId/index.tsx",
      "parent": "/rundown/$rundownId"
    }
  }
}
ROUTE_MANIFEST_END */
