name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
  build-windows-installer:
    name: Build Windows Installer
    runs-on: windows-latest
    needs: create-release
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Prepare Environment
        run: |
          yarn --frozen-lockfile --network-timeout 1000000
        env:
          CI: true
      - name: Build installer
        run: |
          yarn electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: (Debug) List build files
        run: |
          ls dist_electron
  build-linux-installer:
    name: Build Linux Installer
    runs-on: ubuntu-latest
    needs: create-release
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Prepare Environment
        run: |
          yarn --frozen-lockfile --network-timeout 1000000
        env:
          CI: true
      - name: Build installer
        run: |
          yarn electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-macos-installer:
    name: Build MacOS Installer
    runs-on: macos-latest
    needs: create-release
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Prepare Environment
        run: |
          yarn --frozen-lockfile --network-timeout 1000000
        env:
          CI: true
      - name: Build installer
        run: |
          yarn electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
