name: Dependencies Check

on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'

jobs:
  validate-prod-dependencies-packages:
    name: Validate Package production dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - name: Prepare Environment
        run: |
          corepack enable
          yarn install
        env:
          CI: true
      - name: Validate production dependencies
        run: |
          if ! git log --format=oneline -n 1 | grep -q "\[ignore-audit\]"; then
            yarn validate:dependencies
          else
            echo "Skipping audit"
          fi
        env:
          CI: true

  validate-all-dependencies-packages:
    name: Validate all Package dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - name: Prepare Environment
        run: |
          corepack enable
          yarn install
        env:
          CI: true
      - name: Validate production dependencies
        run: |
          yarn validate:dependencies
        env:
          CI: true
      - name: Validate dev dependencies
        run: |
          yarn validate:dev-dependencies
        env:
          CI: true
