name: Node CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'
  pull_request:

jobs:
  lint:
    name: Typecheck and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
      - name: restore node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Prepare Environment
        run: |
          corepack enable
          yarn
        env:
          CI: true
      - name: Run typecheck and linter
        run: |
          yarn build
          yarn lint
        env:
          CI: true

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Enable Corepack with yarn@4.9.1
        run: corepack enable && corepack prepare yarn@4.9.1 --activate

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Run build
        run: yarn build
